export const EffectData = {
    explosion: {
      name: "explode",
      src: "/src/assets/boomEffect.png",
      frameWidth: 69,
      frameHeight: 60,
      animation: {
        key: "explode",
        start: 0,
        end: 24,
        frameRate: 20,
        repeat: 0,
      },
    },
    newExplosion: {
      name: "newExplode",
      src: "/src/assets/destroy.png",
      frameWidth: 517,
      frameHeight: 517,
      animation: {
        key: "newExplode",
        start: 0,
        end: 29,
        frameRate: 15,
        repeat: 0,
      },
    },
    bigHit: {
      name: "bigHitExplode",
      src: "/src/assets/bigHit.png",
      frameWidth: 120,
      frameHeight: 109,
      animation: {
        key: "bigHitExplode",
        start: 0,
        end: 34,
        frameRate: 60,
        repeat: 0,
      },
    },
    airplaneFly: {
        name: "airplaneFly",
        src: "/src/assets/airplaneFly.png",
        frameWidth: 52,
        frameHeight: 92,
        animation: {
            key: "airplaneFly",
            start: 0,
            end: 7,
            frameRate: 8,
            repeat: -1,
        },
    },
    spaceShip: {
      name: "spaceShip",
        src: "/src/assets/spaceShip.png",
        frameWidth: 32,
        frameHeight: 32,
        animation: {
            key: "spaceShip",
            start: 0,
            end: 2,
            frameRate: 3,
            repeat: 0,
        },
    },
    spaceShip_straight: {
        name: "spaceShip_straight",
        src: "/src/assets/spaceShip_straight.png",
        frameWidth: 32,
        frameHeight: 44,
        animation: {
            key: "spaceShip_straight",
            start: 0,
            end: 3,
            frameRate: 16,
            repeat: 0,
        },
    },
    spaceShip_left: {
        name: "spaceShip_left",
        src: "/src/assets/spaceShip_left.png",
        frameWidth: 32,
        frameHeight: 44,
        animation: {
            key: "spaceShip_left",
            start: 0,
            end: 3,
            frameRate: 16,
            repeat: 0,
        },
    },
    spaceShip_right: {
        name: "spaceShip_right",
        src: "/src/assets/spaceShip_right.png",
        frameWidth: 32,
        frameHeight: 44,
        animation: {
            key: "spaceShip_right",
            start: 0,
            end: 3,
            frameRate: 16,
            repeat: 0,
        },
    },
    announcer: {
        name: "announcer",
        src: "/src/assets/announcer.png",
        frameWidth: 32,
        frameHeight: 32,
        animation: {
            key: "announcer",
            start: 0,
            end: 4,
            frameRate: 10,
            repeat: -1,
        },
    }
  };